# Problem Statement: https://www.hackerrank.com/challenges/more-than-75-marks/problem
# Difficulty: Easy
# Score: 15

-MySQL query:

SELECT NAME FROM 
(SELECT DISTINCT NAME, ID FROM STUDENTS WHERE MARKS > 75 ORDER BY RIGHT(NAME,3), ID) AS DATA

-MySQL query with FUNCTION RIGHT():

SELECT NAME FROM STUDENTS 
WHERE MARKS > 75 
ORDER BY RIGHT(NAME, 3), ID

-MySQL query with SUBSTRING():

SELECT NAME FROM STUDENTS 
WHERE MARKS > 75 
ORDER BY SUBSTRING(NAME, -3, 3), ID
